apiVersion: v1
kind: Service
metadata:
  name: appminio
spec:
  selector:
    io.kompose.service: minio
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
    nodePort: 31675
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - server
        - /export
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
        image: minio/minio
        name: minio
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
