apiVersion: v1
kind: Service
metadata:
  name: appweb
spec:
  selector:
    io.kompose.service: website
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 31907
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: website
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: GET_HOSTS_FROM
          value: dns
        image: docker.io/mitouthibaut14/gestion
        name: website
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
